name: nom_nom_express
description: A new Flutter project.

# Remove the 'publish_to' line if you wish to publish to pub.dev
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Adjust the SDK version as needed

dependencies:
  http: ^0.13.3  # Use the latest version
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/briyani.jpg
    - assets/burger.jpg
    - assets/crave.jpg
    - assets/fries.jpg
    - assets/getstarted.jpg
    - assets/joos.jpg
    - assets/maggi.jpg
    - assets/profile_picture.jpg
    - assets/sandwich.jpg
    - assets/usapizza.jpg
    - assets/vapourkit.jpg



